# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

# Allows you to run this workflow manually from the Actions ta

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
        # Runs a set of commands using the runners shell
      - name: Odin build
        run: odin build .
