name: Build Odin Examples (Linux)

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

env:
  FORCE_COLOR: "1"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Dependencies
        run: |
          sudo apt update
          sudo apt install -y llvm
          echo "/usr/lib/llvm-18/bin" >> "$GITHUB_PATH"

      - name: Set up Odin
        run: |
          git clone https://github.com/odin-lang/Odin.git --depth 1 --single-branch --branch=master
          cd Odin
          make
          ./odin report

      - name: Build Odin Example
        run: |
          cd path/to/your/example
          ./odin build . -out:ExampleExecutable

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: example-build
          path: ./ExampleExecutable

